# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: markbame/workspace

pipelines:
  branches:
    production:
      - step:
          caches:
            - node
          script: # Modify the commands below to build your repository.
            - npm install
            - npm test
            - sh deploy.bash production
    staging:
      - step:
          caches:
            - node
          script: # Modify the commands below to build your repository.
            - npm install
            - npm test
            - sh deploy.bash staging
